# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.bd
# Block Designs: The module: 'simpledesign' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_0 || ORIG_REF_NAME==simpledesign_microblaze_0_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_dlmb_v10_1 || ORIG_REF_NAME==simpledesign_dlmb_v10_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_v10_1 || ORIG_REF_NAME==simpledesign_ilmb_v10_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_bram_if_cntlr_1/simpledesign_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==simpledesign_ilmb_bram_if_cntlr_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_axi_periph_1/simpledesign_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_axi_periph_1 || ORIG_REF_NAME==simpledesign_microblaze_0_axi_periph_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_mdm_1_1 || ORIG_REF_NAME==simpledesign_mdm_1_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_xbar_1/simpledesign_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_xbar_1 || ORIG_REF_NAME==simpledesign_xbar_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_lmb_bram_0/simpledesign_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_lmb_bram_0 || ORIG_REF_NAME==simpledesign_lmb_bram_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_0 || ORIG_REF_NAME==simpledesign_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_dlmb_v10_1 || ORIG_REF_NAME==simpledesign_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_v10_1 || ORIG_REF_NAME==simpledesign_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_bram_if_cntlr_1/simpledesign_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_mdm_1_1 || ORIG_REF_NAME==simpledesign_mdm_1_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_xbar_1/simpledesign_xbar_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_lmb_bram_0/simpledesign_lmb_bram_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simpledesign'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.bd
# Block Designs: The module: 'simpledesign' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_0 || ORIG_REF_NAME==simpledesign_microblaze_0_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_dlmb_v10_1 || ORIG_REF_NAME==simpledesign_dlmb_v10_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_v10_1 || ORIG_REF_NAME==simpledesign_ilmb_v10_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_bram_if_cntlr_1/simpledesign_ilmb_bram_if_cntlr_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==simpledesign_ilmb_bram_if_cntlr_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_axi_periph_1/simpledesign_microblaze_0_axi_periph_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_axi_periph_1 || ORIG_REF_NAME==simpledesign_microblaze_0_axi_periph_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_mdm_1_1 || ORIG_REF_NAME==simpledesign_mdm_1_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_xbar_1/simpledesign_xbar_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_xbar_1 || ORIG_REF_NAME==simpledesign_xbar_1}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_lmb_bram_0/simpledesign_lmb_bram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_lmb_bram_0 || ORIG_REF_NAME==simpledesign_lmb_bram_0}]

# IP: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_microblaze_0_0 || ORIG_REF_NAME==simpledesign_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_microblaze_0_0/simpledesign_microblaze_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_dlmb_v10_1 || ORIG_REF_NAME==simpledesign_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_dlmb_v10_1/simpledesign_dlmb_v10_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_ilmb_v10_1 || ORIG_REF_NAME==simpledesign_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_v10_1/simpledesign_ilmb_v10_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_ilmb_bram_if_cntlr_1/simpledesign_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_mdm_1_1 || ORIG_REF_NAME==simpledesign_mdm_1_1}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_mdm_1_1/simpledesign_mdm_1_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simpledesign_rst_Clk_100M_0 || ORIG_REF_NAME==simpledesign_rst_Clk_100M_0}]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_rst_Clk_100M_0/simpledesign_rst_Clk_100M_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_0_0/simpledesign_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_0_0 || ORIG_REF_NAME==simpledesign_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_1_0/simpledesign_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_1_0 || ORIG_REF_NAME==simpledesign_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_gpio_2_0/simpledesign_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_gpio_2_0 || ORIG_REF_NAME==simpledesign_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_xbar_1/simpledesign_xbar_1_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_lmb_bram_0/simpledesign_lmb_bram_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/ip/simpledesign_axi_uartlite_0_0/simpledesign_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==simpledesign_axi_uartlite_0_0 || ORIG_REF_NAME==simpledesign_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simpledesign'. Do not add the DONT_TOUCH constraint.
