# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k410tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.cache/wt [current_project]
set_property parent.project_path C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.bd
set_property used_in_implementation false [get_files -all C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.dcp]
set_property is_locked true [get_files C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.bd]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top simpledesign -part xc7k410tffg900-2 -mode out_of_context
rename_ref -prefix_all simpledesign_
write_checkpoint -noxdef simpledesign.dcp
catch { report_utilization -file simpledesign_utilization_synth.rpt -pb simpledesign_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.runs/simpledesign_synth_1/simpledesign.dcp C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.ip_user_files/ip/simpledesign]} {
  catch { 
    file copy -force C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_stub.v C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.ip_user_files/ip/simpledesign
  }
}

if {[file isdir C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.ip_user_files/ip/simpledesign]} {
  catch { 
    file copy -force C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.srcs/sources_1/bd/simpledesign/simpledesign_stub.vhdl C:/Users/trtran/MicroBlaze/mb-DMAboot/vivado/workingfolders/mbDMAboot_example/mbDMAboot_example.ip_user_files/ip/simpledesign
  }
}
